"""
OpenTrade CLI - init command

初始化配置文件和数据库
"""

import os
import json
from pathlib import Path
from datetime import datetime
import typer
from rich import print as rprint

app = typer.Typer(help="Initialize OpenTrade configuration and database")


@app.command()
def init(
    force: bool = typer.Option(False, "--force", "-f", help="Overwrite existing config"),
    interactive: bool = typer.Option(True, "-i/--no-interactive", help="Interactive mode"),
):
    """
    Initialize OpenTrade configuration

    Creates:
    - config.yaml (main configuration)
    - .env (environment variables)
    - data/ directory
    """
    rprint("[bold]🚀 OpenTrade Initialization[/bold]")

    # 检查是否已初始化
    config_path = Path("config.yaml")
    if config_path.exists() and not force:
        rprint("[yellow]⚠️  OpenTrade already initialized (use --force to reinitialize)[/yellow]")
        return

    # 默认配置模板
    config_content = '''# OpenTrade Configuration
# Generated by opentrade init

app:
  name: "OpenTrade"
  environment: "development"
  debug: true
  log_level: "INFO"

exchanges:
  hyperliquid:
    enabled: true
    testnet: true
    api_key: ""
    api_secret: ""
  binance:
    enabled: false
    testnet: true
    api_key: ""
    api_secret: ""

database:
  host: "localhost"
  port: 5432
  name: "opentrade"
  user: "postgres"
  password: "postgres"
  pool_size: 10

redis:
  host: "localhost"
  port: 6379
  db: 0

web:
  host: "0.0.0.0"
  port: 8000
  cors_origins:
    - "http://localhost:3000"

telegram:
  enabled: false
  token: ""
  chat_id: ""

ai:
  default_model: "deepseek"
  deepseek:
    enabled: true
    api_key: ""
    base_url: "https://api.deepseek.com/v1"

risk:
  max_leverage: 2.0
  max_position_size: 0.1
  max_daily_loss: 0.08
  stop_loss_default: 0.035
  take_profit_default: 0.07
'''

    env_content = '''# OpenTrade Environment Variables
# Copy to .env and fill in your API keys

# Exchange API Keys
HYPERLIQUID_API_KEY=
HYPERLIQUID_API_SECRET=

# AI Models
DEEPSEEK_API_KEY=
OPENAI_API_KEY=
ANTHROPIC_API_KEY=

# Database
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/opentrade

# Redis
REDIS_URL=redis://localhost:6379/0

# Telegram
TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=
'''

    # 写入配置文件
    with open("config.yaml", "w") as f:
        f.write(config_content)

    with open(".env", "w") as f:
        f.write(env_content)

    # 创建数据目录
    Path("data").mkdir(exist_ok=True)
    Path("data/strategies").mkdir(exist_ok=True)
    Path("data/logs").mkdir(exist_ok=True)

    rprint("[green]✅ Initialization complete![/green]")
    rprint("")
    rprint("Next steps:")
    rprint("  1. Edit .env with your API keys")
    rprint("  2. Run: opentrade gateway")
    rprint("  3. Open http://localhost:8000/docs for API")


if __name__ == "__main__":
    app()
