"""
OpenTrade Notifiers - Telegram Integration

Telegram 通知器
"""

from datetime import datetime
from typing import Any
from opentrade.notifiers import BaseNotifier


class TelegramNotifier(BaseNotifier):
    """Telegram 通知器"""

    def __init__(
        self,
        token: str,
        chat_id: str,
        enabled: bool = True,
    ):
        self.token = token
        self.chat_id = chat_id
        self.enabled = enabled
        self.name = "Telegram"
        self._api_url = f"https://api.telegram.org/bot{token}"

    async def send_message(self, message: str, **kwargs) -> bool:
        """发送消息"""
        if not self.enabled:
            return False

        try:
            import httpx

            async with httpx.AsyncClient() as client:
                response = await client.post(
                    f"{self._api_url}/sendMessage",
                    json={
                        'chat_id': self.chat_id,
                        'text': message,
                        'parse_mode': 'Markdown',
                    },
                    timeout=10,
                )
                return response.status_code == 200

        except Exception as e:
            print(f"[Telegram] Send failed: {e}")
            return False

    async def send_trade_notification(
        self,
        symbol: str,
        side: str,
        quantity: float,
        price: float,
        pnl: float | None = None,
        **kwargs,
    ) -> bool:
        """发送交易通知"""
        emoji = "🟢" if side.upper() == "BUY" else "🔴"
        pnl_text = f"\nPnL: `{pnl:.2f}`" if pnl is not None else ""

        message = f"""{emoji} *{side.upper()}* {symbol}
Qty: `{quantity}`
Price: `{price:,.2f}`{pnl_text}

_Generated by OpenTrade_
"""
        return await self.send_message(message)

    async def send_alert(
        self,
        alert_type: str,
        message: str,
        severity: str = "INFO",
        **kwargs,
    ) -> bool:
        """发送告警"""
        emoji = {
            "INFO": "ℹ️",
            "WARNING": "⚠️",
            "ERROR": "🚨",
            "CRITICAL": "⛔",
        }.get(severity, "📢")

        full_message = f"""{emoji} *{severity}* - {alert_type}

{message}

_Time: {datetime.utcnow().isoformat()}_
"""
        return await self.send_message(full_message)

    async def send_daily_summary(self, stats: dict) -> bool:
        """发送每日汇总"""
        message = f"""📊 *Daily Summary*

Balance: `${stats.get('balance', 0):,.2f}`
Today's PnL: `{stats.get('daily_pnl', 0):,.2f}`
Win Rate: `{stats.get('win_rate', 0):.1%}`
Trades: `{stats.get('trades', 0)}`

_Generated by OpenTrade_
"""
        return await self.send_message(message)


def create_telegram_notifier(
    token: str,
    chat_id: str,
    enabled: bool = True,
) -> TelegramNotifier:
    """创建 Telegram 通知器"""
    return TelegramNotifier(token=token, chat_id=chat_id, enabled=enabled)
